MCU = RP2040
BOOTLOADER = rp2040

# Features
VIA_ENABLE = yes
TAP_DANCE_ENABLE = yes
OLED_ENABLE = yes
OS_DETECTION_ENABLE = yes
LTO_ENABLE = yes
VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_KEYPRESSES = yes

# Special Features
EXTRAKEY_ENABLE = yes
QMK_SETTINGS = yes
MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
WPM_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Vial-Features
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes